<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.cosinuscode.swing</groupId>
        <artifactId>spring-swing-boot-starter-parent</artifactId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>

    <groupId>org.cosinuscode.streamer</groupId>
    <artifactId>streamer-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>streamer-ui</module>
        <module>streamer-api</module>
        <module>streamer-file</module>
        <module>streamer-ftp</module>
        <module>streamer-pack</module>
        <module>streamer-database</module>
        <module>streamer-geo</module>
        <module>streamer-drive</module>
        <module>streamer-strava</module>
    </modules>
    <packaging>pom</packaging>
    <name>Streamer Parent</name>

    <properties>
        <spring-cloud.version>5.0.2</spring-cloud.version>
        <commons-net.version>3.13.0</commons-net.version>
        <commons-compress.version>1.28.0</commons-compress.version>
        <jenetics-jpx.version>3.2.1</jenetics-jpx.version>
        <google-api.version>v3-rev197-1.25.0</google-api.version>
        <google-api-client.version>1.25.0</google-api-client.version>
        <google-auth-oath2.version>1.34.0</google-auth-oath2.version>
        <google-oath-jetty.version>1.39.0</google-oath-jetty.version>
        <google-maps.version>2.2.0</google-maps.version>
        <ojdbc11.version>23.26.2.0.0</ojdbc11.version>
        <jooq.version>3.21.6</jooq.version>
        <junrar.version>7.6.0</junrar.version>
        <xz.version>1.12</xz.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-openfeign-core</artifactId>
                <version>${spring-cloud.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-openfeign</artifactId>
                <version>${spring-cloud.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-file</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-ftp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-drive</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-pack</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-geo</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-database</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.cosinuscode.streamer</groupId>
                <artifactId>streamer-strava</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jenetics</groupId>
                <artifactId>jpx</artifactId>
                <version>${jenetics-jpx.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>${commons-net.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.junrar</groupId>
                <artifactId>junrar</artifactId>
                <version>${junrar.version}</version>
            </dependency>
            <dependency>
                <groupId>org.tukaani</groupId>
                <artifactId>xz</artifactId>
                <version>${xz.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.apis</groupId>
                <artifactId>google-api-services-drive</artifactId>
                <version>${google-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.auth</groupId>
                <artifactId>google-auth-library-oauth2-http</artifactId>
                <version>${google-auth-oath2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.api-client</groupId>
                <artifactId>google-api-client</artifactId>
                <version>${google-api-client.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.oauth-client</groupId>
                <artifactId>google-oauth-client-jetty</artifactId>
                <version>${google-oath-jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.maps</groupId>
                <artifactId>google-maps-services</artifactId>
                <version>${google-maps.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.database.jdbc</groupId>
                <artifactId>ojdbc11</artifactId>
                <version>${ojdbc11.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jooq</groupId>
                <artifactId>jooq</artifactId>
                <version>${jooq.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
