/*
 * Copyright 2025 Cosinus Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.cosinus.streamer.ui.action.execute.copy;

import org.cosinus.streamer.api.BinaryStreamer;
import org.cosinus.streamer.api.Streamer;
import org.cosinus.streamer.api.stream.pipeline.binary.BinaryPipelineStrategy;
import org.cosinus.streamer.api.stream.pipeline.error.AbortPipelineConsumeException;
import org.cosinus.streamer.api.stream.pipeline.error.SkipPipelineConsumeException;
import org.cosinus.swing.boot.SwingApplicationFrame;
import org.cosinus.swing.dialog.DialogHandler;
import org.cosinus.swing.dialog.DialogOption;
import org.cosinus.swing.format.FormatHandler;
import org.cosinus.swing.image.icon.IconHandler;
import org.cosinus.swing.image.icon.IconSize;
import org.cosinus.swing.translate.Translator;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Objects;
import java.util.stream.IntStream;

import static java.lang.String.format;
import static java.util.Optional.ofNullable;
import static javax.swing.JOptionPane.*;
import static org.cosinus.streamer.ui.action.execute.copy.CopyOverwriteOption.*;
import static org.cosinus.swing.context.ApplicationContextInjector.injectContext;

public class CopyBinaryStrategy implements BinaryPipelineStrategy {

    @Autowired
    SwingApplicationFrame applicationFrame;

    @Autowired
    private Translator translator;

    @Autowired
    protected DialogHandler dialogHandler;

    @Autowired
    private IconHandler iconHandler;

    @Autowired
    private FormatHandler formatHandler;

    private final BinaryStreamer source;

    private final BinaryStreamer target;

    private final CopyStrategy copyStrategy;

    private boolean overwriteCurrentTarget;

    private boolean skipCurrentTargets;

    private boolean appendSourceToCurrentTargets;

    private boolean resumeCopy;

    public CopyBinaryStrategy(BinaryStreamer source, BinaryStreamer target, CopyStrategy copyStrategy) {

        injectContext(this);
        this.source = source;
        this.target = target;
        this.copyStrategy = copyStrategy;
    }

    @Override
    public boolean shouldRetryOnFail() {
        DialogOption optionValue = dialogHandler.retryWithSkipDialog(applicationFrame,
            translator.translate("act_copy_error_write", target.getPath()));
        if (optionValue == DialogOption.ABORT) {
            throw new AbortPipelineConsumeException("Copy aborted by user after data consume failed");
        }
        if (optionValue == DialogOption.SKIP) {
            long skippedBytes = source.getSize();
            throw new SkipPipelineConsumeException(skippedBytes, format("Accepted to skip %d bytes", skippedBytes));
        }
        return optionValue == DialogOption.RETRY;
    }

    @Override
    public boolean shouldContinueWhenCannotResume(long skippedBytes, long bytesToSkip) {
        int option = dialogHandler.showConfirmationDialog(applicationFrame,
            translator.translate("act_copy_resume_not_match", source.getPath(), target.getPath()),
            translator.translate("act_copy_resume_confirmation"),
            YES_NO_CANCEL_OPTION);
        return option == YES_OPTION;
    }

    @Override
    public boolean shouldContinueWhenCheckFailed() {
        return dialogHandler.confirm(applicationFrame,
            translator.translate("act_copy_check_error", source.getPath(), target.getPath()));
    }

    @Override
    public boolean shouldSkipExistingTarget() {
        return shouldSkipCurrentTargets() ||
            shouldSkipAllExistingTargets() ||
            (shouldOverwriteAllExistingTargetsIfOlder() && !isOlderThan(target, source));
    }

    private boolean isOlderThan(Streamer<?> streamerToCompare, Streamer<?> streamerToCompareTo) {
        return streamerToCompare.lastModified() < streamerToCompareTo.lastModified();
    }

    public BinaryStreamer prepareTarget() {
        return target.exists() ?
            isForceNewInsteadOverwrite() ?
                applyAutogeneratedName(target) :
                applyOverwriteOption(source, target) :
            target;
    }

    private BinaryStreamer applyAutogeneratedName(BinaryStreamer target) {
        return IntStream.range(1, Integer.MAX_VALUE)
            .mapToObj(Integer::toString)
            .map(i -> target.getName() + "(" + i + ")")
            .map(newName -> createRenamedStreamer(target, newName))
            .filter(Objects::nonNull)
            .filter(streamer -> !streamer.exists())
            .findFirst()
            .orElse(target);
    }

    private BinaryStreamer applyOverwriteOption(BinaryStreamer source, BinaryStreamer target) {

        if (shouldSkipAllExistingTargets()) {
            throw new SkipPipelineConsumeException(source.getSize());
        }

        if (shouldOverwriteAllExistingTargets() ||
            shouldOverwriteAllExistingTargetsIfOlder()) {
            return target;
        }

        CopyOverwriteOption overwriteOption = dialogHandler.showCustomOptionDialog(
            applicationFrame,
            translator.translate("act_copy_target_exists"),
            getOverwriteMessage(source, target),
            DEFAULT_OPTION,
            INFORMATION_MESSAGE,
            iconHandler.findIconByFile(source.getPath().toFile(), IconSize.X32).orElse(null),
            3,
            550,
            values());

        if (overwriteOption == null || overwriteOption == CANCEL) {
            throw new AbortPipelineConsumeException("Copy aborted by user during asking for target overwrite.");
        }

        if (overwriteOption == RENAME) {
            BinaryStreamer newTarget = dialogHandler.showInputDialog(applicationFrame,
                    translator.translate("act_copy_new_name"))
                .map(newName -> createRenamedStreamer(target, newName))
                .orElseThrow(() -> new AbortPipelineConsumeException(
                    format("Copy aborted during choosing new name for existing target %s", target.getPath())));
            return newTarget.exists() ?
                applyOverwriteOption(source, newTarget) :
                newTarget;
        }
        overwriteOption.apply(this);

        if (shouldSkipExistingTarget()) {
            throw new SkipPipelineConsumeException(source.getSize());
        }

        return target;
    }

    protected String getOverwriteMessage(BinaryStreamer source, BinaryStreamer target) {
        return format("%s\n%s\n\n%s\n%s\n\n",
            translator.translate("act_copy_already_exists", target.getPath()),
            target.getPath(),
            translator.translate("act_copy_source_modified",
                formatHandler.formatDate(source.lastModified()),
                formatHandler.formatMemorySize(source.getSize())),
            translator.translate("act_copy_target_modified",
                formatHandler.formatDate(target.lastModified()),
                formatHandler.formatMemorySize(target.getSize())));
    }

    private BinaryStreamer createRenamedStreamer(BinaryStreamer streamerToRename, String newName) {
        return ofNullable(streamerToRename)
            .map(Streamer::getParent)
            .map(parent -> parent.create(parent.getPath().resolve(newName), false))
            .map(Streamer::binaryStreamer)
            .orElse(null);
    }

    public boolean shouldOverwriteCurrentTarget() {
        return overwriteCurrentTarget;
    }

    public void overwriteCurrentTarget() {
        this.overwriteCurrentTarget = true;
    }

    public boolean shouldSkipCurrentTargets() {
        return skipCurrentTargets;
    }

    public void skipCurrentTarget() {
        this.skipCurrentTargets = true;
    }

    @Override
    public boolean shouldAppend() {
        return appendSourceToCurrentTargets;
    }

    public void appendSourceToCurrentTarget() {
        this.appendSourceToCurrentTargets = true;
    }

    @Override
    public boolean shouldResume() {
        return resumeCopy;
    }

    public void resumeCopy() {
        this.resumeCopy = true;
    }

    public boolean shouldOverwriteAllExistingTargets() {
        return copyStrategy.shouldOverwriteAllExistingTargets();
    }

    public void overwriteAllExistingTargets() {
        copyStrategy.overwriteAllExistingTargets();
    }

    public boolean shouldOverwriteAllExistingTargetsIfOlder() {
        return copyStrategy.shouldOverwriteAllExistingTargetsIfOlder();
    }

    public void overwriteAllExistingTargetsIfOlder() {
        copyStrategy.overwriteAllExistingTargetsIfOlder();
    }

    public boolean shouldSkipAllExistingTargets() {
        return copyStrategy.shouldSkipAllExistingTargets();
    }

    public void skipAllExistingTargets() {
        copyStrategy.skipAllExistingTargets();
    }

    public boolean isForceNewInsteadOverwrite() {
        return copyStrategy.isForceNewInsteadOverwrite();
    }

    @Override
    public boolean shouldCheck() {
        return copyStrategy.shouldCheck();
    }

    @Override
    public int getPipelineRate() {
        return target.getTransferRate();
    }
}
